#!/bin/bash
# This script is designed to be started after logs are delivered
# to elasticsearch. Then it waits 'till registry offset reaches file size.
# It can be also launched by hand.

REGISTRY="$1"
keepcycle () {
       	echo -n .
       	sleep 60
       	exec $0 $REGISTRY
}

if [[ "$#" < 1 ]]; then
       	echo "Usage: $0 <registry_file>"
       	exit 1
else
       	if [ -e "$1" ]; then
       		LFNAME=$(cat "$1" | cut -d, -f1 | cut -d: -f2 | sed 's/\"//g')
       		OFFSET=$(cat "$1" | cut -d, -f2 | cut -d: -f2)
       		if [ -e "$LFNAME" ]; then
       			LFSIZE=$(stat -c%s $LFNAME)
       		else
       			keepcycle
       		fi
          
       		if [ -e $LFNAME ] && [ $OFFSET == $LFSIZE ]; then
       			echo
       			echo "$(date): Flushing $LFNAME ($LFSIZE)"
       			rm "$LFNAME"
       		else
       			keepcycle
       		fi
       	else
       		echo "Error: registry file not found."
       	fi
fi
