#!/bin/bash
# This script is designed to be started after logs are delivered 
# to elasticsearch. Then it waits 'till registry offset reaches file size.
# It can be also launched by hand.

#!/bin/bash

if [[ "$#" < 1 ]]; then
	echo "Usage: $0 <registry_file>"
	exit 1
else
	if [ -e "$1" ]; then
		LFNAME=$(cat "$1" | cut -d, -f1 | cut -d: -f2 | sed 's/\"//g')
		OFFSET=$(cat "$1" | cut -d, -f2 | cut -d: -f2)
		if [ -e "$LFNAME" ]; then
			LFSIZE=$(stat -c%s $LFNAME)
		else
			echo "Error: log file not available."
			exit 1
		fi

		if [ -e $LFNAME ] && [ $OFFSET == $LFSIZE ]; then
			echo "$(date): Flushing harvested $LFNAME ($LFSIZE)"
			rm "$LFNAME"
		else
			sleep 30
			exec $0 $1
		fi
	else
		echo "Error: registry file not found."
	fi
fi
